name: Increment Version and Create Tag

on:
  push:
    branches:
      - main

jobs:
  increment-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Bump version and create tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch --tags

        # Get the latest tag
        latest_tag=$(git tag --sort=-v:refname | head -n 1)

        # Increment the minor version
        new_version=$(echo $latest_tag | awk -F. '{print $1 "." ($2+1) "." $3}')

        git tag -a "v${new_version}" -m "Release v${new_version}"
        git push origin "v${new_version}"
